### PR TITLE
Fergul master

### PR DESCRIPTION
**Pull request by geoff-coppertop**
cprint isn't compiling in Arduino so I had to remove it to get this change to work.

### CODE REVIEW

**Comment by drFerg** [comment]
Hmmm, strange, it compiles in my Arduino IDE. Can you post the Arduino compile error and version so I can try and see what's causing it. It's really useful to have the cprint library for debugging purposes.
Also, can you explain why you added the single output option?

**Comment by drFerg** [comment]
I changed my device build to Yun and these errors appeared. I see the yun doesn't have the same hardware defines as the Uno etc. I will look into #define the print stuff and make it disappear for the Yun.

> Arduino: 1.6.4 (Linux), Board: "Arduino Yún"
> 
> Build options changed, rebuilding all
> /home/fergus/sketchbook/libraries/cmdrarduino/cprint.c: In function 'USART0SendByte':
> /home/fergus/sketchbook/libraries/cmdrarduino/cprint.c:8:11: error: 'UCSR0A' undeclared (first use in this function>)>
>   while(!(UCSR0A&(1<<UDRE0))){};
>           ^
> /home/fergus/sketchbook/libraries/cmdrarduino/cprint.c:8:11: note: each undeclared identifier is reported only once for each function it appears in
> /home/fergus/sketchbook/libraries/cmdrarduino/cprint.c:8:22: error: 'UDRE0' undeclared (first use in this function)
>   while(!(UCSR0A&(1<<UDRE0))){};
>                      ^
> /home/fergus/sketchbook/libraries/cmdrarduino/cprint.c:10:3: error: 'UDR0' undeclared (first use in this function)
>   UDR0 = u8Data;
>   ^
> /home/fergus/sketchbook/libraries/cmdrarduino/cprint.c: In function 'USART0ReceiveByte':
> /home/fergus/sketchbook/libraries/cmdrarduino/cprint.c:16:11: error: 'UCSR0A' undeclared (first use in this function)
>   while(!(UCSR0A&(1<<RXC0))){};
>           ^
> /home/fergus/sketchbook/libraries/cmdrarduino/cprint.c:16:22: error: 'RXC0' undeclared (first use in this function)
>   while(!(UCSR0A&(1<<RXC0))){};
> /home/fergus/sketchbook/libraries/cmdrarduino/cprint.c:17:10: error: 'UDR0' undeclared (first use in this function)
>   u8Data=UDR0;
>          ^
> Error compiling.

**Comment by drFerg** [comment]
Ok, I've changed how the cprint library defines the ports and added the correct ports for Yun/Leonardo (32u4) boards which should fix the above issue and remove the need to remove the library altogether. Test it and let me know if it works for you. @geoff-coppertop

**Comment by geoff-coppertop** [comment]
The SINGLE_OUTPUT define let's pin bound solutions that don't require
differential output to drop the OC1B pin output without loss of
functionality. In my case my test platform away from the Yun is a Arduino
Pro Micro from spark fun that uses the same ATmega32U4 processor but only
has 14 pins broken out, I'm then using the pin that would be used by OC1B
as an input for short detection from the LMD18200.

Geoff

**Comment by drFerg** [comment]
Ah I see, sounds good. I will integrate your single_output code into the main branch, as this pull has all the commenting out of the print related functions which should now be fixed. 
Thanks
P.s. I'm curious, how are you doing the differential output instead?

**Comment by geoff-coppertop** [comment]
The differential output isn't needed on the LMD18200 because the signal can be fed to the direction pin and the PWM pin is held high so the bridge output will swing between the rails.

**Comment by drFerg** [comment]
Sweet, that's pretty cool. I'm going to have to get one.

**Pull request closed without merging**
